//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.1
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Easy2.Properties {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Easy2.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대한 현재 스레드의 CurrentUICulture
        ///   속성을 재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap AlterDatabase {
            get {
                object obj = ResourceManager.GetObject("AlterDatabase", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap AlterEvent {
            get {
                object obj = ResourceManager.GetObject("AlterEvent", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap AlterFunction {
            get {
                object obj = ResourceManager.GetObject("AlterFunction", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap AlterIndex {
            get {
                object obj = ResourceManager.GetObject("AlterIndex", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap AlterStoredProcedure {
            get {
                object obj = ResourceManager.GetObject("AlterStoredProcedure", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap AlterTable {
            get {
                object obj = ResourceManager.GetObject("AlterTable", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap AlterTrigger {
            get {
                object obj = ResourceManager.GetObject("AlterTrigger", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap AlterUser {
            get {
                object obj = ResourceManager.GetObject("AlterUser", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap AlterView {
            get {
                object obj = ResourceManager.GetObject("AlterView", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CancelSelection {
            get {
                object obj = ResourceManager.GetObject("CancelSelection", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CloseTab {
            get {
                object obj = ResourceManager.GetObject("CloseTab", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ColorTable {
            get {
                object obj = ResourceManager.GetObject("ColorTable", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Config {
            get {
                object obj = ResourceManager.GetObject("Config", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ConnectDatabase {
            get {
                object obj = ResourceManager.GetObject("ConnectDatabase", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ConnectDatabaseCurrentSetting {
            get {
                object obj = ResourceManager.GetObject("ConnectDatabaseCurrentSetting", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ConnectDatabaseL {
            get {
                object obj = ResourceManager.GetObject("ConnectDatabaseL", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CopyDatabase {
            get {
                object obj = ResourceManager.GetObject("CopyDatabase", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CopySelection {
            get {
                object obj = ResourceManager.GetObject("CopySelection", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CreateDatabase {
            get {
                object obj = ResourceManager.GetObject("CreateDatabase", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CreateEvent {
            get {
                object obj = ResourceManager.GetObject("CreateEvent", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CreateFunction {
            get {
                object obj = ResourceManager.GetObject("CreateFunction", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CreateIndex {
            get {
                object obj = ResourceManager.GetObject("CreateIndex", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CreateStoredProcedure {
            get {
                object obj = ResourceManager.GetObject("CreateStoredProcedure", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CreateTable {
            get {
                object obj = ResourceManager.GetObject("CreateTable", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CreateTrigger {
            get {
                object obj = ResourceManager.GetObject("CreateTrigger", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CreateUser {
            get {
                object obj = ResourceManager.GetObject("CreateUser", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CreateView {
            get {
                object obj = ResourceManager.GetObject("CreateView", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CutSelection {
            get {
                object obj = ResourceManager.GetObject("CutSelection", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DeleteSelection {
            get {
                object obj = ResourceManager.GetObject("DeleteSelection", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Disconnect {
            get {
                object obj = ResourceManager.GetObject("Disconnect", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DisconnectAll {
            get {
                object obj = ResourceManager.GetObject("DisconnectAll", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DropColumn {
            get {
                object obj = ResourceManager.GetObject("DropColumn", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DropDatabase {
            get {
                object obj = ResourceManager.GetObject("DropDatabase", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DropEvent {
            get {
                object obj = ResourceManager.GetObject("DropEvent", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DropFunction {
            get {
                object obj = ResourceManager.GetObject("DropFunction", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DropIndex {
            get {
                object obj = ResourceManager.GetObject("DropIndex", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DropStoredProcedure {
            get {
                object obj = ResourceManager.GetObject("DropStoredProcedure", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DropTable {
            get {
                object obj = ResourceManager.GetObject("DropTable", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DropTrigger {
            get {
                object obj = ResourceManager.GetObject("DropTrigger", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DropView {
            get {
                object obj = ResourceManager.GetObject("DropView", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   예외가 발생하였습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Easy2Exception {
            get {
                return ResourceManager.GetString("Easy2Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   MySQL 서버 연결에 실패하였습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Easy2Exception_Connect {
            get {
                return ResourceManager.GetString("Easy2Exception_Connect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   서버에서 &lt;font color=\&quot;#FF0000\&quot;&gt;DELETE&lt;/font&gt; 명령을 거부하였습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Easy2Exception_DeleteCommandDenied {
            get {
                return ResourceManager.GetString("Easy2Exception_DeleteCommandDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   쿼리문 실행을 실패하였습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Easy2Exception_ExecuteQuery {
            get {
                return ResourceManager.GetString("Easy2Exception_ExecuteQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   파일을 읽는 중 예외가 발생하였습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Easy2Exception_FileRead {
            get {
                return ResourceManager.GetString("Easy2Exception_FileRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   파일을 쓰는 중 예외가 발생하였습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Easy2Exception_FileWrite {
            get {
                return ResourceManager.GetString("Easy2Exception_FileWrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   서버에서 &lt;font color=\&quot;#FF0000\&quot;&gt;INSERT&lt;/font&gt; 명령을 거부하였습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Easy2Exception_InsertCommandDenied {
            get {
                return ResourceManager.GetString("Easy2Exception_InsertCommandDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   서버에서 &lt;font color=\&quot;#FF0000\&quot;&gt;SELECT&lt;/font&gt; 명령을 거부하였습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Easy2Exception_SelectCommandDenied {
            get {
                return ResourceManager.GetString("Easy2Exception_SelectCommandDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   서버에서 &lt;font color=\&quot;#FF0000\&quot;&gt;SHOW&lt;/font&gt; 명령을 거부하였습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Easy2Exception_ShowCommandDenied {
            get {
                return ResourceManager.GetString("Easy2Exception_ShowCommandDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   서버에서 &lt;font color=\&quot;#FF0000\&quot;&gt;UPDATE&lt;/font&gt; 명령을 거부하였습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Easy2Exception_UpdateCommandDenied {
            get {
                return ResourceManager.GetString("Easy2Exception_UpdateCommandDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   서버에서 &lt;font color=\&quot;#FF0000\&quot;&gt;USE&lt;/font&gt; 명령을 거부하였습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Easy2Exception_UseCommanDenied {
            get {
                return ResourceManager.GetString("Easy2Exception_UseCommanDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   MySQL 서버 연결에 성공하였습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Easy2Message_ConnectSuccess {
            get {
                return ResourceManager.GetString("Easy2Message_ConnectSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   연결테스트과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Easy2Message_ConnectTest {
            get {
                return ResourceManager.GetString("Easy2Message_ConnectTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   객체를 삭제하시겠습니까?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Easy2Message_DeleteQuestion {
            get {
                return ResourceManager.GetString("Easy2Message_DeleteQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   입력한 비밀번호가 서로 일치하지 않습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Easy2Message_DoNotMatchPassword {
            get {
                return ResourceManager.GetString("Easy2Message_DoNotMatchPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &apos;{0}&apos; 항목이 입력되지 않았습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Easy2Message_EmptyItem {
            get {
                return ResourceManager.GetString("Easy2Message_EmptyItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   질문과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Easy2Message_Question {
            get {
                return ResourceManager.GetString("Easy2Message_Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Easy To MySQL과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Easy2Message_Title {
            get {
                return ResourceManager.GetString("Easy2Message_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &apos;{0}&apos; 사용자 정보가 수정되었습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Easy2Message_UserAlterSuccessfully {
            get {
                return ResourceManager.GetString("Easy2Message_UserAlterSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &apos;{0}&apos; 사용자가 만들어졌습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Easy2Message_UserCreatedSuccessfully {
            get {
                return ResourceManager.GetString("Easy2Message_UserCreatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &apos;{0}&apos; 사용자를 삭제 하시겠습니까?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Easy2Message_UserDeleteQuestion {
            get {
                return ResourceManager.GetString("Easy2Message_UserDeleteQuestion", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Error {
            get {
                object obj = ResourceManager.GetObject("Error", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ExecuteAllQuery {
            get {
                object obj = ResourceManager.GetObject("ExecuteAllQuery", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ExecuteQuery {
            get {
                object obj = ResourceManager.GetObject("ExecuteQuery", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ExecuteSelectQuery {
            get {
                object obj = ResourceManager.GetObject("ExecuteSelectQuery", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ExportDatabase {
            get {
                object obj = ResourceManager.GetObject("ExportDatabase", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   ..\\..\\dat\\connection.dat과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FilePath_ConnectionData {
            get {
                return ResourceManager.GetString("FilePath_ConnectionData", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap FindData {
            get {
                object obj = ResourceManager.GetObject("FindData", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FolderClose {
            get {
                object obj = ResourceManager.GetObject("FolderClose", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FolderOpen {
            get {
                object obj = ResourceManager.GetObject("FolderOpen", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FormStyle {
            get {
                object obj = ResourceManager.GetObject("FormStyle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GoToLine {
            get {
                object obj = ResourceManager.GetObject("GoToLine", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Help {
            get {
                object obj = ResourceManager.GetObject("Help", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap HelpDocument {
            get {
                object obj = ResourceManager.GetObject("HelpDocument", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImportDatabase {
            get {
                object obj = ResourceManager.GetObject("ImportDatabase", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap OpenFile {
            get {
                object obj = ResourceManager.GetObject("OpenFile", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap OpenFileNewTab {
            get {
                object obj = ResourceManager.GetObject("OpenFileNewTab", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap OpenObject {
            get {
                object obj = ResourceManager.GetObject("OpenObject", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PasteToClipboard {
            get {
                object obj = ResourceManager.GetObject("PasteToClipboard", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PrivilegeUser {
            get {
                object obj = ResourceManager.GetObject("PrivilegeUser", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap QueryEditor {
            get {
                object obj = ResourceManager.GetObject("QueryEditor", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap QueryWizard {
            get {
                object obj = ResourceManager.GetObject("QueryWizard", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap QuitApplication {
            get {
                object obj = ResourceManager.GetObject("QuitApplication", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RedoAction {
            get {
                object obj = ResourceManager.GetObject("RedoAction", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RefreshObjectBrowser {
            get {
                object obj = ResourceManager.GetObject("RefreshObjectBrowser", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RenameL {
            get {
                object obj = ResourceManager.GetObject("RenameL", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ReplaceData {
            get {
                object obj = ResourceManager.GetObject("ReplaceData", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RestoreDatabase {
            get {
                object obj = ResourceManager.GetObject("RestoreDatabase", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SaveAsFile {
            get {
                object obj = ResourceManager.GetObject("SaveAsFile", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SaveFile {
            get {
                object obj = ResourceManager.GetObject("SaveFile", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SchemaDesigner {
            get {
                object obj = ResourceManager.GetObject("SchemaDesigner", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SelectAll {
            get {
                object obj = ResourceManager.GetObject("SelectAll", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Settings {
            get {
                object obj = ResourceManager.GetObject("Settings", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SwitchNextTab {
            get {
                object obj = ResourceManager.GetObject("SwitchNextTab", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SwitchPreviousTab {
            get {
                object obj = ResourceManager.GetObject("SwitchPreviousTab", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap TreeColumn {
            get {
                object obj = ResourceManager.GetObject("TreeColumn", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap TreeDatabase {
            get {
                object obj = ResourceManager.GetObject("TreeDatabase", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap TreeEvent {
            get {
                object obj = ResourceManager.GetObject("TreeEvent", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap TreeFunction {
            get {
                object obj = ResourceManager.GetObject("TreeFunction", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap TreeIndex {
            get {
                object obj = ResourceManager.GetObject("TreeIndex", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap TreePkIndex {
            get {
                object obj = ResourceManager.GetObject("TreePkIndex", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap TreePrimaryKey {
            get {
                object obj = ResourceManager.GetObject("TreePrimaryKey", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap TreeServerActivate {
            get {
                object obj = ResourceManager.GetObject("TreeServerActivate", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap TreeServerDeactivate {
            get {
                object obj = ResourceManager.GetObject("TreeServerDeactivate", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap TreeStoredProc {
            get {
                object obj = ResourceManager.GetObject("TreeStoredProc", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap TreeTable {
            get {
                object obj = ResourceManager.GetObject("TreeTable", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap TreeTrigger {
            get {
                object obj = ResourceManager.GetObject("TreeTrigger", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap TreeView {
            get {
                object obj = ResourceManager.GetObject("TreeView", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap TruncateDatabase {
            get {
                object obj = ResourceManager.GetObject("TruncateDatabase", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap TruncateTable {
            get {
                object obj = ResourceManager.GetObject("TruncateTable", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap UndoAction {
            get {
                object obj = ResourceManager.GetObject("UndoAction", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap UpdateCheck {
            get {
                object obj = ResourceManager.GetObject("UpdateCheck", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
